version: '2'
services:
  db:
    restart: always
    image: mysql
    container_name: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tips
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
